#!/usr/bin/env bash
#
# Bash SSH VPN wrapper
#
set -e

if [[ ${#} -lt 1 ]]; then
  echo "Usage: ${0} [SSH_USER@]SSH_SERVER [NETWORK1, NETWORK2, ... NETWORKx]"
  exit 1
fi

declare -r SSH_SERVER=${1}; shift
declare -r NETWORKS=${@}

declare -r IP_BASE=192.168.245
declare -r TUNNEL_ID_PATH=~/.xiringuito/tunnel_id
declare -r TUNNEL_ID_FILE=${TUNNEL_ID_PATH}/${SSH_SERVER}

if [[ ! -f ${TUNNEL_ID_FILE} ]]; then
  mkdir -p ${TUNNEL_ID_PATH}
  let GENERATED_ID=${RANDOM}%50+1
  echo ${GENERATED_ID} >${TUNNEL_ID_FILE}
fi

declare -r TUNNEL_ID=$(cat ${TUNNEL_ID_FILE})
declare -r REMOTE_PATH="/tmp/xiringuito.${TUNNEL_ID}"

declare -r SSH_OPTS="-oLogLevel=QUIET -oConnectTimeout=10"

cd $(dirname ${0})

trap teardown EXIT

function teardown() {
  echo "Tearing down tunnel..."
  ./scripts/client-teardown.sh ${TUNNEL_ID}
  ssh ${SSH_OPTS} ${SSH_SERVER} pkill -f ${REMOTE_PATH}/server-execute.sh
}

echo "TUNNEL ID: ${TUNNEL_ID}"
./scripts/client-setup.sh ${TUNNEL_ID} ${IP_BASE}

for NETWORK in ${NETWORKS}; do
   echo "> ROUTE: ${NETWORK}"
  ./scripts/client-route.sh ${TUNNEL_ID} ${NETWORK}
done

ssh ${SSH_OPTS} ${SSH_SERVER} mkdir -p ${REMOTE_PATH}
scp -oLogLevel=QUIET ./scripts/server-*.sh ${SSH_SERVER}:${REMOTE_PATH} >/dev/null

ssh ${SSH_OPTS} ${SSH_SERVER} ${REMOTE_PATH}/server-setup.sh ${TUNNEL_ID} ${IP_BASE}
sleep 1; echo -n "SERVER: ${SSH_SERVER} ... "
ssh ${SSH_OPTS} -w ${TUNNEL_ID}:${TUNNEL_ID} ${SSH_SERVER} ${REMOTE_PATH}/server-execute.sh ${TUNNEL_ID} ${IP_BASE}
